name: 编译 winlator-glibc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install host deps
        run: |
          sudo apt update
          sudo apt install -y git

      - name: Start container
        run: |
          docker run -d --privileged --name build-env ubuntu:24.04 tail -f /dev/null

      - name: Install container deps
        run: |
          docker exec build-env bash -c "
            apt update &&
            apt install -y git build-essential curl sudo
          "

      - name: Clone repo
        run: |
          docker exec build-env bash -c "
            cd /root &&
            git clone https://github.com/moze30/glibc-packages.git
          "

      - name: Setup environment
        run: |
          docker exec build-env bash -c "
            set -e
            cd /root/glibc-packages
            ./get-build-package.sh
            ./scripts/setup-ubuntu.sh
            ./scripts/setup-cgct.sh
          "

      - name: Disable linux-api-headers
        run: |
          docker exec build-env bash -c "
            cd /root/glibc-packages/gpkg
            rm -rf linux-api-headers*
          "

      - name: Build ALL packages
        run: |
          docker exec build-env bash -c "
            set -e
            cd /root/glibc-packages
            export TERMUX_PACKAGE_LIBRARY=glibc

            for pkg in \$(ls gpkg); do
              echo '========== BUILDING' \$pkg '=========='
              ./build-package.sh -a aarch64 \$pkg || exit 1
            done
          "

      - name: Collect deb files
        run: |
          docker exec build-env bash -c "
            mkdir -p /root/artifacts
            cp /root/glibc-packages/output/*.deb /root/artifacts/
            cd /root/artifacts
            tar czvf /root/all-packages.tar.gz *.deb
          "

      - name: Copy artifact
        run: |
          docker cp build-env:/root/all-packages.tar.gz ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: winlator-glibc-packages
          path: ./all-packages.tar.gz

      - name: Cleanup
        if: always()
        run: |
          docker stop build-env || true
          docker rm build-env || true
